Expenditure_tracker/Exp_trac_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name='Exp_trac_app'

#applications URLS file
#Contains URLS for signup,logout,addition of expense page, editing of expense page
#and For view the expenses page.

urlpatterns=[
path('logout/',auth_views.LogoutView.as_view(),name='logout'),
path('signup/',views.SignUp.as_view(),name='signup'),
path('addexp/',views.AddExp.as_view(),name='addexp'),
path('editexp/',views.EditExp.as_view(),name='editexp'),
path('viewexp/',views.ViewExp.as_view(),name='viewexp'),
]

Expenditure_tracker/Expenditure_tracker/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

from . import views


#Projects URLS file
#Contains URLS for admin,index,thankyou,about,login pages
#also contain link for applications URLs file

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Exp_trac_app.urls',namespace='expenditures')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('index',views.HomePage.as_view(),name='home'),
    path('thanks',views.ThanksPage.as_view(),name='thanks'),
    path('about',views.AboutPage.as_view(),name='about'),
    path('',auth_views.LoginView.as_view(template_name='Exp_trac_app/login.html', redirect_authenticated_user=True),name='login'),


]

Expenditure_tracker/templates/about.html
{% extends 'base.html' %}
{% block content %}
<div class="row" align="center">

    <div class="container">
      <div class="col-sm-2"></div>
      <div class="col-sm-8">
        <h1>Expense Tracker</h1>
        <br>
        <h4>About this website</h4>
        <p>This website is a way to keep the track of your monthly expenses, you can add and view your expenses for daily expenditures. The expenses that you'll add will be according to the things you are spending on.So that you can keep a track of the things you are spending more or less money.</p>
        {% if user.is_authenticated %}
          <a href="{% url 'login' %}"><button type="button" class="btn btn-primary">Back to Home Page</button></a>
        {% else %}
          <a href="{% url 'login' %}"><button type="button" class="btn btn-primary">Back to Login Page</button></a>
        {% endif %}

      </div>
      <div class="col-sm-2"></div>
{% endblock %}

Expenditure_tracker/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Expenditure calculater</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body >

    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    {% if user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'home' %}">Expense Tracker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav w-100">

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          <li class="nav-item dropdown ml-auto">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon glyphicon-user"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'Exp_trac_app:addexp'%}">Add todays expense</a>
              <a class="dropdown-item" href="{% url 'Exp_trac_app:editexp' %}">Edit previous days expenses</a>
              <a class="dropdown-item" href="{% url 'Exp_trac_app:viewexp'%}">View your monthly expenses</a>
              <a class="dropdown-item" href="{% url 'Exp_trac_app:logout'%}">Logout</a>
            </div>
          </li>
        {% else %}
        <a class="navbar-brand" href="{% url 'login'%}">Expense Tracker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav w-100">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          <li class="nav-item dropdown ml-auto">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon glyphicon-user"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'Exp_trac_app:signup' %}">Signup</a>
              <a class="dropdown-item" href="{% url 'login' %}">Login</a>
            </div>
          </li>
        {% endif %}
    </ul>
  </div>
</nav>


    <h1 align="center">Expense Tracker</h1>
    <hr>
    <br>

    <div >
      {% block content %}

      {% endblock %}
    </div>

  </body>
</html>

Expenditure_tracker/templates/index.html
{% extends 'base.html' %}
{% block content%}
<div class="row" align="center">

    <div class="container">
      <div class="col-sm-3"></div>
      <div class="col-sm-6">

        <h1 align="center">Expense Tracker</h1>
        <hr>
        <br>
        <h2>Welcome {{user.username}}</h2>
        <h4>Any updates on the expenditures?</h4>

          <a href="{% url 'Exp_trac_app:addexp'%}"><pre><button type="button" class="btn btn-primary">Add todays expenses</button></pre></a>
          <br>
          <a href="{% url 'Exp_trac_app:editexp' %}"><button type="button" class="btn btn-secondary">Edit previous expenses</button></a>
          <br> <br> <br>
          <a href="{% url 'Exp_trac_app:viewexp'%}"><button type="button" class="btn btn-success">View monthly expenses</button></a>
      </div>
      <div class="col-sm-3"></div>



  </div>
{% endblock%}

Expenditure_tracker/templates/thanks.html
{% extends 'base.html' %}
{% block content%}

<div class="container">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <h1>Expense Tracker</h1>
    <br>
    <h4>Thank You</h4>


    <a href="{% url 'login' %}"><button type="button" class="btn btn-primary">Back to Login Page</button></a>

  </div>
  <div class="col-sm-4"></div>
{% endblock%}